### PR TITLE
Add test cases for undo

### PR DESCRIPTION
**Pull request by turtle96**

### CODE REVIEW

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/code-quality 

pls check

**Comment by marcusngwenjian** [comment]
image
@CS2103AUG2016-W15-C3/testing Please test

**Comment by ZuoZhuolin** [comment]
screen shot 2016-11-07 at 2 52 14 pm
All test cases pass, but there are exceptions when run the junit test.

**Comment by marcusngwenjian** [comment]
@turtle96 Kindly resolve.

**Comment by turtle96** [comment]
There's no issue on my comp
image
 if it's passing on travis and junit it should be ok

**Pull request merged**
