### PR TITLE
Add StartDate EndDate Fix UI Add JUnit tests

### LINKED ISSUE #86: Add starting date for tasks

### PR DESCRIPTION
**Pull request by marcusngwenjian**
This closes #86 
## Add Start Date and End Date
- Edit and add these 2 attributes to task
## Fix UI
- Hide TaskPriority and TaskType from GUI
- Display date in the format of NAME_OF_DAY_OF_WEEK, DAY MONTH YEAR
## Add JUnit tests
- Add tests for Paser class
- Add tests for TaskDate class
- Add tests for TaskTime class

### CODE REVIEW

**Comment by marcusngwenjian** [comment]
@CS2103AUG2016-W15-C3/testing Ready for testing (Do check for gradle build)
@CS2103AUG2016-W15-C3/documentation Ready for review

**Comment by turtle96** [comment]
Testing pass. Gradle build can be built.

Suggestions: 
1. It handles period by day like "add smth from mon to fri", but does not seem to handle period for time i.e. "add smth from mon 2pm to fri 6pm"
2. If possible, good to add tests for more task example such as event, deadline etc :)

**Comment by marcusngwenjian** [comment]
@turtle96 

> It handles period by day like "add smth from mon to fri", but does not seem to handle period for time i.e. "add smth from mon 2pm to fri 6pm"

User have to either type from mon from 2pm to fri to 2pm OR from mon to fri from 2pm to 6pm. Each date and time has to be preceeded by by/on/at/from/to, else the queue data structure used in the parser will more difficult to implement. Will be documenting this in the user guide. Thanks for the suggestion

**Comment by turtle96** [comment]
Ok thanks for clarification. As long as there is support for that format it's okay.

**Comment by Mamtha3005** [comment]
Documentation Reviewed

**Pull request merged**
