### PR TITLE
Update description and UI in README.md

### PR DESCRIPTION
**Pull request by marcusngwenjian**
@CS2103AUG2016-W15-C3/documentation Ready for review

### CODE REVIEW

**Comment by Mamtha3005** [comment]
Reviewed.
@CS2103AUG2016-W15-C3/integration Ready for integration

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/code-quality 

Please review
Is the following section needed, or changes should be made to remove reference to level 3 addressbook
"What's different from level 3:
A more sophisticated GUI that includes a list panel and an in-built Browser.
More test cases, including automated GUI testing.
Support for Build Automation using Gradle and for Continuous Integration using Travis CI."

**Comment by marcusngwenjian** [comment]
Changes made.
@CS2103AUG2016-W15-C3/documentation Ready for review.

**Comment by Mamtha3005** [comment]
Reviewed.
@CS2103AUG2016-W15-C3/integration Ready for integration

**Pull request merged**
