### PR TITLE
Edit: Add Junit test and fix bugs

### LINKED ISSUE #177: Editing of floating task has no display
image

### PR DESCRIPTION
**Pull request by Mamtha3005**
This fixes #177

### CODE REVIEW

**Comment by Mamtha3005** [comment]
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/integration 
Ready for review

**Comment by marcusngwenjian** [comment]
Although it fixes #177 , but new bug arises.
Refer to issue #191

**Comment by turtle96** [comment]
same bug found, #191 

change "do" to "does" 
image

**Comment by turtle96** [comment]
@Mamtha3005 please review

**Comment by Mamtha3005** [comment]
This now closes #191

**Comment by Mamtha3005** [comment]
@CS2103AUG2016-W15-C3/testing Made changes already.

**Comment by marcusngwenjian** [comment]
@Mamtha3005  JUnit test fail. please revise

**Pull request closed without merging**
