### PR TITLE
change invalid command style of command box

### PR DESCRIPTION
**Pull request by turtle96**
bg - purple
text - white

### CODE REVIEW

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/code-quality 
@CS2103AUG2016-W15-C3/documentation 

pls review

**Comment by Mamtha3005** [comment]
Better to keep the original since red color sort of infers wrong and easier for user to understand whats going on.

**Comment by ZuoZhuolin** [comment]
Test reviewed, but I also think red is better.

**Comment by marcusngwenjian** [comment]
Code quality reviewed
Agreed with above suggestion. Red serves as a warning to user. Purple does not seem to fit the context.

**Comment by turtle96** [comment]
@Mamtha3005 @ZuoZhuolin @marcusngwj 
generally my concern is the current shade of red can be painful for the eyes, if anyone could recommend a better colour, i can edit it in

or it you prefer it as it is, then we don't merge

**Comment by turtle96** [comment]
@Mamtha3005 @ZuoZhuolin @marcusngwj 
how about this red

**Comment by Mamtha3005** [comment]
I still feel that the original colour and font colour is better because the new red is similar to the priority red.

**Pull request closed without merging**
