### PR TITLE
Update code standard

### PR DESCRIPTION
**Pull request by turtle96**
#158

### CODE REVIEW

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/code-quality 
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/testing 

Please review

**Comment by Mamtha3005** [comment]
Documentation Reviewed

**Comment by marcusngwenjian** [comment]
Code Quality reviewed

**Comment by marcusngwenjian** [comment]
Testing reviewed
@CS2103AUG2016-W15-C3/integration Ready for integration

**Pull request merged**
