### PR TITLE
Modify priority colours ui

### PR DESCRIPTION
**Pull request by turtle96**
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/code-quality 
@CS2103AUG2016-W15-C3/documentation 

Please review

image

### CODE REVIEW

**Comment by Mamtha3005** [comment]
Documentation Reviewed

**Comment by ZuoZhuolin** [comment]
Test reviewed

**Comment by marcusngwenjian** [comment]
Code quality reviewed
@CS2103AUG2016-W15-C3/integration Ready for integration

*Take note of the concurrency exception still exist in this PR.

**Comment by turtle96** [comment]
@marcusngwj 
all tests pass on travis, please refer to travis checks

**Pull request merged**
