### PR TITLE
Change edit command

### LINKED ISSUE #170: Redo edit command

### PR DESCRIPTION
**Pull request by Mamtha3005**
New format edit idx st:  et:  sd:   ed:  desc:     p:     .. allows user to edit as many para as he wants in 1 line

This closes #170

### CODE REVIEW

**Comment by Mamtha3005** [comment]
@CS2103AUG2016-W15-C3/code-quality 
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/documentation 
Ready for testing

**Comment by turtle96** [comment]
@Mamtha3005 Please resolve merge conflict of Parser

**Comment by marcusngwenjian** [comment]
Refer to issues #177 and #184

**Comment by marcusngwenjian** [comment]
Testing reviewed.
<br>
Code quality reviewed. However, methods are too long. Please improve SLAP.

@Mamtha3005 Please make the changes by branching out from master after this PR is merged.

**Pull request merged**
