### PR TITLE
fix bug for undo tests

### PR DESCRIPTION
**Pull request by turtle96**
@Mamtha3005 @marcusngwj @ZuoZhuolin 
please pull and run all tests and check all pass

### CODE REVIEW

**Comment by Mamtha3005** [comment]
Donumentation Reviewed. Please refer to #120

**Comment by marcusngwenjian** [comment]
Code quality reviewed

**Comment by marcusngwenjian** [comment]
Testing Passed

**Comment by marcusngwenjian** [comment]
Ready for integration

**Pull request merged**
