### PR TITLE
Implement undo done, undone, and edit

### LINKED ISSUE #164: Undo Edit

### PR DESCRIPTION
**Pull request by turtle96**
close #164 , #163

### CODE REVIEW

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/code-quality 

review pls

**Comment by turtle96** [comment]
resolve #203

**Comment by turtle96** [comment]
closes bug #203 and tests #209

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/testing 
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/code-quality

**Comment by ZuoZhuolin** [comment]
Test reviewed

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/code-quality

pls remember to review, thank you :D

**Pull request merged**
