### PR TITLE
Improve clear command

### LINKED ISSUE #162: Add check for clear

### PR DESCRIPTION
**Pull request by turtle96**
add confirmation dialog, note that this needs mouse click for cancel (enter key works for "OK")
closes #162

### CODE REVIEW

**Comment by turtle96** [comment]
@CS2103AUG2016-W15-C3/code-quality 
@CS2103AUG2016-W15-C3/documentation 
Pls review

@CS2103AUG2016-W15-C3/testing 
Please check that tests run correctly, since clear command now has a confirmation dialog

**Comment by Mamtha3005** [comment]
Documentation Reviewed

**Comment by marcusngwenjian** [comment]
@turtle96 Refer to issue #182 for bug

**Comment by marcusngwenjian** [comment]
Code quality reviewed.
Testing reviewed.

**Pull request merged**
