### PR TITLE
Implement find command search by tags

### PR DESCRIPTION
**Pull request by turtle96**

### CODE REVIEW

**Comment by turtle96** [comment]
Please review.
@CS2103AUG2016-W15-C3/code-quality 
@CS2103AUG2016-W15-C3/documentation 
@CS2103AUG2016-W15-C3/testing

**Comment by marcusngwenjian** [comment]
Code Quality Reviewed

**Comment by Mamtha3005** [comment]
Documentation reviewed

**Comment by ZuoZhuolin** [comment]
Testing Reviewed

**Pull request merged**
